# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImageCameraDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'GPUImage'
  # Pods for GPUImageCameraDemo

  target 'GPUImageCameraDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPUImageCameraDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
